package application.products.exceptions;
import application.main.Main;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
public class ProductAlreadyExistsException extends Exception {
    /* Generated by Spoon */
    private Main mm;

    /* Generated by Spoon */
    private LogManager lm;

    /* Generated by Spoon */
    private static Logger logger = LogManager.getLogger(ProductAlreadyExistsException.class.getName());
}