package applicationSpooned.main.exceptions;
import applicationSpooned.main.Main;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
public class NoSuchDisplayException extends Exception {
    /* Generated by Spoon */
    private Main mm;

    /* Generated by Spoon */
    private LogManager lm;

    /* Generated by Spoon */
    private static Logger logger = LogManager.getLogger(NoSuchDisplayException.class.getName());
}