package application.products;
import application.main.Main;
import java.util.Date;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
public class Product {
    /* Generated by Spoon */
    private Main mm;

    /* Generated by Spoon */
    private LogManager lm;

    /* Generated by Spoon */
    private static Logger logger = LogManager.getLogger(Product.class.getName());

    private final String id;

    private String name;

    private double price;

    private Date expirationDate;

    public Product(String id, String name, double price, Date expirationDate) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.expirationDate = expirationDate;
    }

    public String getId() {
        /* Generated by Spoon */
        logger.info("{" + "\"user\" : \"" + (Main.getUserContext() == null ? null : Main.getUserContext().getId()) + "\"" + ", " + "\"method\" : \"" + "getId" + "\"" + ", " + "\"parameters\" : " + "[" + "]" + "}");
        return id;
    }

    public String getName() {
        /* Generated by Spoon */
        logger.info("{" + "\"user\" : \"" + (Main.getUserContext() == null ? null : Main.getUserContext().getId()) + "\"" + ", " + "\"method\" : \"" + "getName" + "\"" + ", " + "\"parameters\" : " + "[" + "]" + "}");
        return name;
    }

    public void setName(String name) {
        /* Generated by Spoon */
        logger.info("{" + "\"user\" : \"" + (Main.getUserContext() == null ? null : Main.getUserContext().getId()) + "\"" + ", " + "\"method\" : \"" + "setName" + "\"" + ", " + "\"parameters\" : " + "[" + "\"" + name + "\"" + "]" + "}");
        this.name = name;
    }

    public double getPrice() {
        /* Generated by Spoon */
        logger.info("{" + "\"user\" : \"" + (Main.getUserContext() == null ? null : Main.getUserContext().getId()) + "\"" + ", " + "\"method\" : \"" + "getPrice" + "\"" + ", " + "\"parameters\" : " + "[" + "]" + "}");
        return price;
    }

    public void setPrice(double price) {
        /* Generated by Spoon */
        logger.info("{" + "\"user\" : \"" + (Main.getUserContext() == null ? null : Main.getUserContext().getId()) + "\"" + ", " + "\"method\" : \"" + "setPrice" + "\"" + ", " + "\"parameters\" : " + "[" + "\"" + price + "\"" + "]" + "}");
        this.price = price;
    }

    public Date getExpirationDate() {
        /* Generated by Spoon */
        logger.info("{" + "\"user\" : \"" + (Main.getUserContext() == null ? null : Main.getUserContext().getId()) + "\"" + ", " + "\"method\" : \"" + "getExpirationDate" + "\"" + ", " + "\"parameters\" : " + "[" + "]" + "}");
        return expirationDate;
    }

    public void setExpirationDate(Date expirationDate) {
        /* Generated by Spoon */
        logger.info("{" + "\"user\" : \"" + (Main.getUserContext() == null ? null : Main.getUserContext().getId()) + "\"" + ", " + "\"method\" : \"" + "setExpirationDate" + "\"" + ", " + "\"parameters\" : " + "[" + "\"" + expirationDate + "\"" + "]" + "}");
        this.expirationDate = expirationDate;
    }

    public Product copy() {
        /* Generated by Spoon */
        logger.info("{" + "\"user\" : \"" + (Main.getUserContext() == null ? null : Main.getUserContext().getId()) + "\"" + ", " + "\"method\" : \"" + "copy" + "\"" + ", " + "\"parameters\" : " + "[" + "]" + "}");
        // retourne une copie du produit
        return new Product(id, name, price, expirationDate);
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Product)) {
            return false;
        }
        Product p = ((Product) (o));
        if (p.getId().equals(((Product) (o)).getId())) {
            return true;
        }
        return false;
    }

    @Override
    public String toString() {
        return ((((((("[id : " + id) + "][nom : ") + name) + "][prix : ") + price) + "][date limite : ") + expirationDate) + "]";
    }
}